import { PrismaClient } from '@prisma/client';
import OpenAI from 'openai';

const prisma = new PrismaClient();
const openai = new OpenAI(); // Uses env OPENAI_API_KEY globally

async function testGeneration() {
  console.log('[MASTER ENGINE] Striking OpenAI Graph Node for physical output...');

  // Create a dummy product
  const product = await prisma.product.upsert({
    where: { id: 'test-product-123' },
    update: {},
    create: { id: 'test-product-123', name: 'Bridgebox Pro', workspaceId: (await prisma.workspace.findFirst())?.id || 'fail', price: 99 }
  });

  // Create a dummy campaign
  const campaign = await prisma.campaign.upsert({
    where: { id: 'auto-test-123' },
    update: {},
    create: {
      id: 'auto-test-123',
      name: 'Initial Bridgebox Monetization Funnel',
      status: 'active',
      workspaceId: (await prisma.workspace.findFirst())?.id || 'fail',
      productId: product.id
    }
  });

  const completion = await openai.chat.completions.create({
    model: "gpt-4o",
    messages: [
      {
        role: "system",
        content: "You are the Instaflow Master Content Architect. You generate ultra-viral, scroll-stopping Instagram Reels hooks and caption layouts designed explicitly for monetization. Output raw JSON without backticks."
      },
      {
        role: "user",
        content: `Generate a viral Instagram Hook and Caption for a new post. Focus on: "Automation and AI SaaS scaling to $10k/month". Output EXACTLY in JSON format: { "hook": "...", "caption": "...", "format": "reel" } without markdown blocks.`
      }
    ]
  });

  const responseText = completion.choices[0].message.content || '{}';
  const aiData = JSON.parse(responseText.replace(/```json/g, '').replace(/```/g, '').trim());

  const asset = await prisma.contentAsset.create({
    data: {
      campaignId: campaign.id,
      title: aiData.hook || 'Viral Asset',
      assetType: aiData.format || 'reel',
      status: 'reviewed', 
      notes: aiData.caption || 'Generated by Instaflow Master AI'
    }
  });

  console.log('✅ OUTPUT CONFIRMED IN POSTGRES LEDGER:');
  console.log('--- HOOK: ', asset.title);
  console.log('--- CAPTION (Truncated): ', asset.notes?.substring(0, 100) + '...');
}

testGeneration()
  .then(() => process.exit(0))
  .catch(console.error);
